---
title: Sleep, food, nappy
author: Dad
date: '2021-08-26'
slug: sleep-food-nappy
categories: []
tags: []
---

## Here we go 

I am 6 weeks into my Shared Parental Leave (SPL). I will be spending 4 months with Joel, my son who was born at the end of 2020 during the coronavirus pandemic. I have wanted to spend some of this time writing a blog about my experience on Shared Parental Leave for a number of reasons. 

1. I want to capture some memories of our time together which I can look back on in the future to remind myself of what we did together (I have a truly bad memory)

2. I want to write a little about the experience, in case there are other dads having children and thinking about doing Shared Parental Leave

3. I am a geek. My day job involves playing with open source software called R, and I wanted to learn a little about how to write a blog using R

I am not writing this blog to share with anyone in particular. My only thoughts are that I might share it with Joel one day (if all of the underpinning processes that publish this blog are still functional in the future). If you happen upon this and find it particularly boring, I'm sorry, it's probably because it is boring! Don't hold it against me.

Agreeing to do SPL was a no-brainer for me. There is no way Natalie could keep happy while doing a year of maternity leave, and if she wanted to cut it short then I would have missed an opportunity. That sounds like my decision was made for me, but in reality the chance of taking a long break from work to spend an extended period with Joel was amazing. I was sad I couldn't do more in Kirsten's first year, but Natalie and my situation was such that it wasn't really financially possible. 

## My fears

I had a few fears coming into this.

* Would I be able to engage and bond with Joel?
* Would I be aimless and spend my whole time on my phone?
* Would I feel like the only Dad in the world of Mums?
* Four months is a long time. Whenever I think about what I was doing 4 months ago it feels like an age ago. How would I get through four months?
* I was actually worried about being able to keep Joel alive, maybe not realistically, but it was something on my mind. I feel silly writing this, but up to going on SPL Natalie had control and I was always playing the supporting extra who needed to be prompted regularly to say his lines.

This last point was my starting point for my SPL. Having had memories of taking Kirsten for days out but forgetting the packed bag at home, or leaving the bag on a bus, I needed a failsafe way to achieve this minimal level of parenting. My early motto became "sleep, food, nappy." 
