---
title: Shared Parental Leave
author: Seb
date: '2021-09-10'
slug: shared-parental-leave
categories: []
tags: []
weight: 30
---

This post is to explain where we are with Shared Parental Leave in England at the moment and describe it for people who are thinking about taking it.

Essentially, [Shared Parental Leave](https://www.gov.uk/shared-parental-leave-and-pay) (SPL) is a way of sharing 50 weeks of leave, and 37 weeks of pay between the parents (it can be used for adoption and also when using a surrogate to have a baby). It is a legal requirement for employers to offer it, but the way it is implemented everywhere is different. Anecdotally, smaller employers find it challenging to implement it.

It is an important opportunity for families in many ways. It gives mothers the opportunity to return to work sooner if they wanted, without the worry of paying or finding for additional childcare, and hence having a child should have a lower impact on their career aspirations. It also allows the father the opportunity to have an extended period of time off work to spend with the new-born child and continue to get paid for it.

There are different ways you can structure the 50 weeks of SPL. It is possible to use the weeks consecutively between the parents, one after the other. Or you can overlap for all or some of the time, so both parents can make use of this rare opportunity to be together and with the new-born child for an extended period.

Our aims with our SPL was to maximise the time we spent with Joel without being financially impacted. We also hoped that Natalie could breastfeed him from birth for a few months. This was quite a challenge to arrange, even in the Civil Service. I think it was because SPL is still relatively new, and here are so many different combinations of how employees can make use of it that we really needed to work through the application with both our Department HR teams. Below is an image that simplistically (I hope) outlines our options for SPL.

```{r infographic, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=3}
library(ggplot2)
library(dplyr)

df <- tibble(
  option = c("Option 1", 
             "Option 2", "Option 2",
             "Option 3", "Option 3",
             "Option 4", "Option 4"),
  person = c("Mum", 
             "Both parents", "Paid childcare",
             "Dad first", "Mum",
             "Mum", "Dad last"),
  value = c(1, 
            0.5, 0.5,
            0.5, 0.5,
            0.6, 0.4)
) %>% 
  mutate(person = factor(person,
                         levels = c("Dad first", "Mum", "Dad last",
                                    "Both parents", "Paid childcare")),
         option = factor(option,
                         levels = paste("Option", 4:1)))

ggplot(df, aes(x = option, y = value, fill = person)) +
  geom_col() +
  scale_fill_brewer(palette = "Set1",
                    name = "") +
  theme_minimal() + 
  coord_flip() +
  theme(axis.title = element_blank()) +
  scale_y_reverse(labels = c("Start of year (week 0)",
                             "End of year (week 50)"),
                  breaks = 1:0)
```

Option 1 would simply have been Natalie taking 50 weeks of Maternity Leave. She would have been paid, roughly, full pay for a chunk of it, then reduced pay for another chunk, then statutory pay. This was our baseline financially for considering other options.

Option 2 would have been lovely! It would have been the two of us having 25 weeks off together at the start, and then returning to work and finding childcare for Joel for the remainder of the year (and beyond). This option would have left us a few grand worse off than Option 1 due to paying for childcare (as we don't have grandparents that live locally enough to support in that way).

Option 3 is where I would have taken the first 25 weeks off with Joel and Natalie would have returned to work after her compulsory Maternity Leave (2 weeks I think). Then I would have handed over to Natalie at the halfway stage to see out the rest of the year. We wouldn't have achieved our ambition to breast feed for the first few months as Natalie wouldn't have been around enough to do so, and I am not Super Dooper Dad, just Super Dad, so I would have struggled.

Option 4 was our preferred option. Natalie takes SPL first, then hands over to me after about 7 months. This is what we have ended up doing, but getting to the solution wasn't as straight forward as it might appear. The HR departments from both of our organisations said that once Maternity Leave starts, the first chunk of full pay begins. Then the pay incrementally decreases based on the timings in the policy. As I was being paid more than Natalie it would have been preferable for our household that I received the full pay, so we can have the same income as we would in Option 1. After some negotiation and analysis of the legislation we managed to agree to structure the pay as such that the weeks that the full pay occurred coincided with my portion of SPL.

In reality, we have actually had a one month cross over period in the middle where we had a holiday as it also coincided with Kirsten's summer holiday from school.

## Terminology

I wanted to add a section on terminology. This is really for anyone happening upon this blog and considering SPL. SPL is different from Paternity Leave (or Adoption Support (Paternity) Leave - I think this is what my organisation calls it). SPL is additional to any Paternity Leave your employer offers. My organisation offers 6 weeks full pay Paternity Leave, which I believe is extremely generous.