---
title: Coming to the end
author: Dad
date: '2021-10-19'
slug: coming-to-the-end
categories: []
tags: []
---

I have under a month left of my SPL. It has genuinely flown by - I really can't believe it. I think it is a mixture of many things; spending time with Joel, the weekly routine, having time with Kirsten after school, seeing her develop and mature enormously (especially these first few weeks in Year 1), Natalie being extremely busy with work, a few trips here and there with grandparents and wider family, and me being off work and not having to worry about it at all. It really has been a very happy few months for me (and hopefully the rest of the family). I will miss it. If any would-be Dads come across this post and are considering SPL, I really really can't stress how great it is and that the opportunity should be taken.

One of the big differences between SPL and Daddy-daycare we've noticed in the past couple of months is that in SPL I have the main responsibility of everything around Joel. It's a small point, but it feels important to me. Previously, I may have taken Kirsten (when she was a baby) out for some time, but I would need help with timings for sleep, feeds, nappies etc etc. Because I spend so much time with Joel the roles are reversed. It means I don't feel like a passive support parent. I can listen to whimpers/cries/sounds Joel makes and I usually know what they mean. Also, from time to time Mum will even ask me what he wants. I'm making a much bigger deal about this than I should - I have spent over 3 month with him, but I suppose it means Joel and I have bonded and alleviates my concerns that I had when I started around not knowing what to do and whether I would bond with him.

So from mid-November Joel will be going into nursery 5 days a week. He'll be 10$\frac{1}{2}$ months old. I'm sad about this happening though I think he'll enjoy it. He loves to play and explore, which he'll get lots of opportunities to do at nursery. He's not spent an awful lot of time with other children, but he has played with quite a few - so I don't have worries about him socialising. It's just sad that this period has come to an end and it does feel like a lot of time that he'll be away from us having spent such an enormous amount of time together. He's been away from Mum and me during the day for a couple of short periods up to now and he's been quite sad in those times, so I think it will be a difficult start. Hopefully after a short amount of time he'll get used to it and thrive.